# coding=utf-8
# Copyright (C) 2024-2025 Golden_Hoe,HOE Software Team.
# AI Generate Information: Some GUI part generated by ChatGPT/Google Gemini.
# AI生成提示：部分GUI实现使用ChatGPT/Google Gemini生成。

import sys
import os
import json
import psutil
import logging
from PyQt5.QtWidgets import (QApplication, QMainWindow, QWidget, QVBoxLayout, QHBoxLayout,
                             QPushButton, QComboBox, QFileDialog, QMessageBox,
                             QLabel, QLineEdit, QPlainTextEdit, QScrollArea,
                             QGroupBox, QStackedWidget, QListWidget, QListWidgetItem,
                             QTextBrowser, QCheckBox)
from PyQt5.QtCore import Qt, QThread, pyqtSignal, QProcess, QTimer, QCoreApplication, QSettings
from PyQt5.QtGui import QFont, QTextCursor, QIcon
import urllib.request
import datetime

# ==================== 配置日志 ====================
# 获取当前时间并格式化为文件名
log_filename = datetime.datetime.now().strftime("MCSEasy_log_%Y-%m-%d-%H-%M-%S.log")

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s - %(levelname)s - %(message)s",
    handlers=[
        logging.FileHandler(log_filename),
        logging.StreamHandler()
    ]
)
logger = logging.getLogger(__name__)
# ==================== 全局常量和辅助函数 ====================
SETTINGS_FILE = "mcseasy_settings.meconf"
URL_LIST_FILE = "url_list.txt"
VERSION_LIST_FILE = "version_list.txt"
EULA_FILE_NAME = 'eula.txt'
SERVER_PROPERTIES_FILE = 'server.properties'

def load_list_file(filename: str) -> list:
    """从文本文件加载Python列表，兼容PyInstaller打包"""
    try:
        # 检查是否在PyInstaller打包环境中
        if getattr(sys, 'frozen', False):
            base_path = sys._MEIPASS
        else:
            base_path = os.path.dirname(os.path.abspath(__file__))
        
        file_path = os.path.join(base_path, filename)
        
        with open(file_path, 'r', encoding='utf-8') as f:
            content = f.read().strip()
        return eval(content)
    except (FileNotFoundError, IOError) as e:
        logger.error(f'加载文件列表失败，文件不存在或读取错误: {e}')
        return []
    except Exception as e:
        logger.error(f'加载文件列表错误: {e}')
        return []

def check_hardware():
    """检测硬件信息并弹出非阻塞式警告"""
    warn_messages = []
    
    cpu_cores = psutil.cpu_count(logical=False)
    logger.info(f"CPU物理核心数量: {cpu_cores}")
    if cpu_cores < 2:
        warn_messages.append("CPU物理核心数少于2，可能会导致服务器性能偏低。")

    memory = psutil.virtual_memory()
    total_memory_mb = memory.total / 1024**2
    logger.info(f"计算机总内存: {total_memory_mb:.2f} MB")
    if total_memory_mb < 2048:
        warn_messages.append("已安装的运行内存少于2048M，可能会导致服务器性能偏低。")

    current_file_path = os.path.abspath(__file__)
    disk_root = os.path.splitdrive(current_file_path)[0] + os.sep
    try:
        disk_usage = psutil.disk_usage(disk_root)
        disk_free_gb = disk_usage.free / 1024**3
        logger.info(f"当前磁盘可用容量: {disk_free_gb:.2f} GB")
        if disk_free_gb < 8:
            warn_messages.append("磁盘可用空间不足8GB，可能会导致服务器文件无法存放。")
    except Exception as e:
        logger.error(f"无法检查磁盘空间: {e}")

    if warn_messages:
        logger.warning(f"硬件检查结束，共发现{len(warn_messages)}个性能问题。")
        full_message = "硬件检测发现了以下性能问题：\n\n" + "\n".join([f"- {msg}" for msg in warn_messages])
        QTimer.singleShot(100, lambda: QMessageBox.warning(
            None, "警告", full_message, QMessageBox.Ok))
    else:
        logger.info('硬件检查结束，没有发现问题。')

# ==================== 下载线程类 ====================
class DownloadThread(QThread):
    progress_updated = pyqtSignal(int)
    download_finished = pyqtSignal(bool, str)

    def __init__(self, url, save_path):
        super().__init__()
        self.url = url
        self.save_path = save_path
        self._is_stopped = False

    def stop(self):
        self._is_stopped = True

    def run(self):
        try:
            with urllib.request.urlopen(self.url) as response:
                total_size = int(response.headers.get('Content-Length', 0))
                downloaded = 0
                chunk_size = 8192
                filename = os.path.join(self.save_path, os.path.basename(self.url))
                with open(filename, 'wb') as f:
                    while not self._is_stopped:
                        chunk = response.read(chunk_size)
                        if not chunk:
                            break
                        f.write(chunk)
                        downloaded += len(chunk)
                        if total_size > 0:
                            self.progress_updated.emit(int((downloaded / total_size) * 100))
                        QCoreApplication.processEvents()
            if self._is_stopped:
                self.download_finished.emit(False, "下载已取消")
            else:
                self.download_finished.emit(True, filename)
        except Exception as e:
            self.download_finished.emit(False, str(e))

# ==================== 主窗口类 ====================
class ServerDeployWindow(QMainWindow):
    log_signal = pyqtSignal(str)
    
    def __init__(self):
        super().__init__()
        # 添加此行以设置窗口图标，并兼容PyInstaller打包
        if getattr(sys, 'frozen', False):
            icon_path = os.path.join(sys._MEIPASS, 'icon.ico')
        else:
            icon_path = 'icon.ico'
        self.setWindowIcon(QIcon(icon_path))
        self.setWindowTitle("简单 Minecraft 服务器部署工具(MCSEasy) Version-1.2.0.0-RC3-GUIRefactor")
        self.setGeometry(100, 100, 1200, 600)
        self.download_thread = None
        self.server_process = None
        self.server_running = False
        self.has_unsaved_changes = False
        self.config_controls = {}
        self.original_config = {}
        self.current_theme = "light"
        self.log_is_dark = True
        self.stop_timer = None

        self.url_list = load_list_file(URL_LIST_FILE)
        self.version_list = load_list_file(VERSION_LIST_FILE)
        
        self.load_settings()
        self._setup_ui()
        self._apply_styles()
        self._connect_signals()
        
    def load_settings(self):
        """加载用户设置，例如主题和日志颜色"""
        settings = QSettings("MyServerApp", "ServerDeployWindow")
        self.current_theme = settings.value("theme", "light")
        self.log_is_dark = settings.value("log_is_dark", True, type=bool)

    def save_settings(self):
        """保存用户设置"""
        settings = QSettings("MyServerApp", "ServerDeployWindow")
        settings.setValue("theme", self.current_theme)
        settings.setValue("log_is_dark", self.log_is_dark)

    def closeEvent(self, event):
        """在窗口关闭时保存设置"""
        self.save_settings()
        super().closeEvent(event)

    def _setup_ui(self):
        """设置主界面布局和控件"""
        central_widget = QWidget()
        self.setCentralWidget(central_widget)
        main_layout = QHBoxLayout(central_widget)

        # 1. 左侧侧边栏 (Side Menu)
        sidebar_widget = self._create_sidebar()
        main_layout.addWidget(sidebar_widget)

        # 2. 中间内容区域 (QStackedWidget)
        self.content_stacked_widget = self._create_content_stack()
        main_layout.addWidget(self.content_stacked_widget, stretch=2)

        # 3. 右侧日志区域 (Log Panel)
        self.right_widget = QWidget()
        right_layout = QVBoxLayout(self.right_widget)
        self.create_status_label(right_layout)
        
        self.log_widget = QPlainTextEdit()
        self.log_widget.setReadOnly(True)
        self.log_widget.setFont(QFont("Microsoft YaHei", 9, QFont.Bold))
        right_layout.addWidget(self.log_widget)
        
        self.command_input = QLineEdit()
        self.command_input.setPlaceholderText("输入服务器指令（按回车发送）")
        right_layout.addWidget(self.command_input)
        
        main_layout.addWidget(self.right_widget, stretch=3)
    
    def _create_sidebar(self):
        """创建左侧侧边栏，仅包含主页、设置、关于"""
        sidebar = QWidget()
        sidebar.setFixedWidth(200)
        
        layout = QVBoxLayout(sidebar)
        layout.setContentsMargins(0, 0, 0, 0)
        layout.setSpacing(0)

        self.sidebar_list = QListWidget()
        self.sidebar_list.setSelectionMode(QListWidget.SingleSelection)
        self.sidebar_list.setFocusPolicy(Qt.NoFocus)

        self.sidebar_list.addItem(QListWidgetItem("主页"))
        self.sidebar_list.addItem(QListWidgetItem("设置"))
        self.sidebar_list.addItem(QListWidgetItem("关于"))
        
        layout.addWidget(self.sidebar_list)
        return sidebar

    def _create_content_stack(self):
        """创建用于容纳不同页面的堆栈容器"""
        stacked_widget = QStackedWidget()
        stacked_widget.addWidget(self._create_home_page())
        stacked_widget.addWidget(self._create_settings_page())
        stacked_widget.addWidget(self._create_about_page())
        # 将其他功能页面添加到堆栈中，但不在侧边栏中显示
        stacked_widget.addWidget(self._create_download_page())
        stacked_widget.addWidget(self._create_memory_page())
        stacked_widget.addWidget(self._create_config_page())
        return stacked_widget
    
    def _apply_styles(self):
        """应用并配置窗口样式"""
        log_bg_color = "#2a2a2a" if self.log_is_dark else "#f0f0f0"
        log_color = "#d0d0d0" if self.log_is_dark else "#202020"
        
        if self.current_theme == "light":
            style_sheet = f"""
                * {{
                    font-family: 'Segoe UI Variable Display', 'Microsoft YaHei';
                    color: #202020;
                }}
                QMainWindow {{
                    background: qlineargradient(x1:0, y1:0, x2:0, y2:1,
                                                stop:0 #f6f6f6, stop:1 #e9e9e9);
                }}
                QGroupBox {{
                    border: 1px solid #e0e0e0;
                    border-radius: 8px;
                    padding: 10px;
                    margin-top: 10px;
                    background-color: #ffffff;
                }}
                QGroupBox::title {{
                    subcontrol-origin: margin;
                    subcontrol-position: top left;
                    padding: 0 3px;
                    left: 10px;
                    color: #555555;
                }}
                QComboBox {{
                    border: 1px solid #cccccc;
                    border-radius: 4px;
                    padding: 5px 8px;
                    background-color: #ffffff;
                    color: #202020;
                }}
                QComboBox:hover {{
                    border-color: #0078D4;
                }}
                QComboBox::drop-down {{
                    subcontrol-origin: padding;
                    subcontrol-position: top right;
                    width: 20px;
                    border-left-width: 1px;
                    border-left-color: #cccccc;
                    border-left-style: solid;
                    border-top-right-radius: 4px;
                    border-bottom-right-radius: 4px;
                }}
                QComboBox::down-arrow {{
                    image: url(data:image/svg+xml;base64,PHN2ZyB0PSIxNzU1ODM4NDk1OTMzIiBjbGFzcz0iaWNvbiIgdmlld0JveD0iMCAwIDEwMjQgMTAyNCIgdmVyc2lvbj0iMS4xIiB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHAtaWQ9IjE0NjIiIHdpZHRoPSIyMDAiIGhlaWdodD0iMjAwIj48cGF0aCBkPSJNMTAyNCA3NjhIMDBWMjU2aDEwMjR6IiBmaWxsPSIjNTE1MTUxIiBmaWxsLW9wYWNpdHk9IjAiIHAtaWQ9IjE0NjMiPjwvcGF0aD48cGF0aCBkPSJNMjg4IDQxMi44YzAtNi40IDMuMi0xMi44IDkuNi0xOS4yIDkuNi05LjYgMjguOC05LjYgMzguNCAwbDE3OS4yIDE4Mi40IDE3Mi44LTE3NmM5LjYtOS42IDI4LjgtOS42IDM4LjQgMCA5LjYgOS42IDkuNiAyOC44IDAgMzguNGwtMTk1LjIgMTk1LjJjLTkuNiA5LjYtMjguOCA5LjYtMzguNCAwbC0xOTguNC0yMDEuNmMtMy4yLTYuNC02LjQtMTIuOC02LjQtMTkuMnoiIGZpbGw9IiM1MTUxNTEiIHAtaWQ9IjE0NjQiPjwvcGF0aD48L3N2Zz4=);
                    width: 16px;
                    height: 16px;
                }}
                QComboBox QAbstractItemView {{
                    border: 1px solid #cccccc;
                    border-radius: 4px;
                    background-color: #ffffff;
                    selection-background-color: #e0e0e0;
                    selection-color: #202020;
                }}
                QLineEdit, QPushButton {{
                    background-color: #f3f3f3;
                    border: 1px solid #cccccc;
                    padding: 5px 8px;
                    border-radius: 4px;
                }}
                QPushButton:hover {{
                    background-color: #e6e6e6;
                }}
                QPushButton:pressed {{
                    background-color: #dcdcdc;
                }}
                QListWidget {{
                    background-color: #ffffff;
                    border: none;
                    padding-top: 10px;
                }}
                QListWidget::item {{
                    padding: 10px 15px;
                    border-radius: 4px;
                    margin: 5px 10px;
                }}
                QListWidget::item:hover {{
                    background-color: #e6e6e6;
                }}
                QListWidget::item:selected {{
                    background-color: #e0e0e0;
                    border-left: 3px solid #0078D4;
                    font-weight: bold;
                }}
                QPlainTextEdit {{
                    background-color: {log_bg_color};
                    color: {log_color};
                    border: 1px solid #cccccc;
                    border-radius: 8px;
                    font-family: 'Consolas', 'Microsoft Yahei';
                    font-weight: bold;
                }}
                QTextBrowser {{
                    background-color: #ffffff;
                    border: 1px solid #e0e0e0;
                    border-radius: 8px;
                    padding: 10px;
                }}
                #status_label {{
                    background-color: #EB5757;
                    color: white;
                    padding: 4px;
                    border-radius: 6px;
                    min-width: 80px;
                    text-align: center;
                }}
                #actionButton {{
                    font-weight: bold;
                    background-color: #0078D4;
                    color: white;
                    border: none;
                }}
                #actionButton:hover {{
                    background-color: #0063B1;
                }}
                #actionButton:pressed {{
                    background-color: #00569E;
                }}
                #pageActionButton {{
                    font-weight: bold;
                    background-color: #E6E6E6;
                    color: #202020;
                    border: none;
                }}
                #pageActionButton:hover {{
                    background-color: #D6D6D6;
                }}
                #pageActionButton:pressed {{
                    background-color: #C6C6C6;
                }}
                QScrollBar:vertical, QScrollBar:horizontal {{
                    border: none;
                    background-color: #F0F0F0;
                    width: 10px;
                    height: 10px;
                    margin: 0px 0px 0px 0px;
                }}
                QScrollBar::handle:vertical, QScrollBar::handle:horizontal {{
                    background-color: #BFBFBF;
                    min-height: 20px;
                    min-width: 20px;
                    border-radius: 5px;
                }}
                QScrollBar::handle:vertical:hover, QScrollBar::handle:horizontal:hover {{
                    background-color: #A0A0A0;
                }}
                QScrollBar::handle:vertical:pressed, QScrollBar::handle:horizontal:pressed {{
                    background-color: #808080;
                }}
                QScrollBar::add-line:vertical, QScrollBar::sub-line:vertical,
                QScrollBar::add-line:horizontal, QScrollBar::sub-line:horizontal {{
                    border: none;
                    background: none;
                }}
                QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical,
                QScrollBar::add-page:horizontal, QScrollBar::sub-page:horizontal {{
                    background: none;
                }}
            """
        else: # Dark theme
            style_sheet = f"""
                * {{
                    font-family: 'Segoe UI Variable Display', 'Microsoft YaHei';
                    color: #d0d0d0;
                }}
                QMainWindow {{
                    background: qlineargradient(x1:0, y1:0, x2:0, y2:1,
                                                stop:0 #1a1a1a, stop:1 #242424);
                }}
                QGroupBox {{
                    border: 1px solid #3a3a3a;
                    border-radius: 8px;
                    padding: 10px;
                    margin-top: 10px;
                    background-color: #2a2a2a;
                }}
                QGroupBox::title {{
                    subcontrol-origin: margin;
                    subcontrol-position: top left;
                    padding: 0 3px;
                    left: 10px;
                    color: #b0b0b0;
                }}
                QComboBox {{
                    border: 1px solid #555555;
                    border-radius: 4px;
                    padding: 5px 8px;
                    background-color: #333333;
                    color: #d0d0d0;
                }}
                QComboBox:hover {{
                    border-color: #0088ff;
                }}
                QComboBox::drop-down {{
                    subcontrol-origin: padding;
                    subcontrol-position: top right;
                    width: 20px;
                    border-left-width: 1px;
                    border-left-color: #555555;
                    border-left-style: solid;
                    border-top-right-radius: 4px;
                    border-bottom-right-radius: 4px;
                }}
                QComboBox::down-arrow {{
                    image: url(data:image/svg+xml;base64,PHN2ZyB0PSIxNzU1ODM4NDk1OTMzIiBjbGFzcz0iaWNvbiIgdmlld0JveD0iMCAwIDEwMjQgMTAyNCIgdmVyc2lvbj0iMS4xIiB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHAtaWQ9IjE0NjIiIHdpZHRoPSIyMDAiIGhlaWdodD0iMjAwIj48cGF0aCBkPSJNMTAyNCA3NjhIMDBWMjU2aDEwMjR6IiBmaWxsPSIjNTE1MTUxIiBmaWxsLW9wYWNpdHk9IjAiIHAtaWQ9IjE0NjMiPjwvcGF0aD48cGF0aCBkPSJNMjg4IDQxMi44YzAtNi40IDMuMi0xMi44IDkuNi0xOS4yIDkuNi05LjYgMjguOC05LjYgMzguNCAwbDE3OS4yIDE4Mi40IDE3Mi44LTE3NmM5LjYtOS42IDI4LjgtOS42IDM4LjQgMCA5LjYgOS42IDkuNiAyOC44IDAgMzguNGwtMTk1LjIgMTk1LjJjLTkuNiA5LjYtMjguOCA5LjYtMzguNCAwbC0xOTguNC0yMDEuNmMtMy4yLTYuNC02LjQtMTIuOC02LjQtMTkuMnoiIGZpbGw9IiM1MTUxNTEiIHAtaWQ9IjE0NjQiPjwvcGF0aD48L3N2Zz4=);
                    width: 16px;
                    height: 16px;
                }}
                QComboBox QAbstractItemView {{
                    border: 1px solid #555555;
                    border-radius: 4px;
                    background-color: #333333;
                    selection-background-color: #4a4a4a;
                    selection-color: #d0d0d0;
                }}
                QLineEdit, QPushButton {{
                    background-color: #3a3a3a;
                    border: 1px solid #555555;
                    padding: 5px 8px;
                    border-radius: 4px;
                    color: #d0d0d0;
                }}
                QPushButton:hover {{
                    background-color: #4a4a4a;
                }}
                QPushButton:pressed {{
                    background-color: #5a5a5a;
                }}
                QListWidget {{
                    background-color: #1a1a1a;
                    border: none;
                    padding-top: 10px;
                }}
                QListWidget::item {{
                    padding: 10px 15px;
                    border-radius: 4px;
                    margin: 5px 10px;
                }}
                QListWidget::item:hover {{
                    background-color: #2a2a2a;
                }}
                QListWidget::item:selected {{
                    background-color: #3a3a3a;
                    border-left: 3px solid #0088ff;
                    font-weight: bold;
                }}
                QPlainTextEdit {{
                    background-color: {log_bg_color};
                    color: {log_color};
                    border: 1px solid #555555;
                    border-radius: 8px;
                    font-family: 'Consolas', 'Microsoft Yahei';
                    font-weight: bold;
                }}
                QTextBrowser {{
                    background-color: #2a2a2a;
                    border: 1px solid #3a3a3a;
                    border-radius: 8px;
                    padding: 10px;
                    color: #d0d0d0;
                }}
                #status_label {{
                    background-color: #EB5757;
                    color: white;
                    padding: 4px;
                    border-radius: 6px;
                    min-width: 80px;
                    text-align: center;
                }}
                #actionButton {{
                    font-weight: bold;
                    background-color: #0088ff;
                    color: white;
                    border: none;
                }}
                #actionButton:hover {{
                    background-color: #0077ee;
                }}
                #actionButton:pressed {{
                    background-color: #0066dd;
                }}
                #pageActionButton {{
                    font-weight: bold;
                    background-color: #3a3a3a;
                    color: #d0d0d0;
                    border: none;
                }}
                #pageActionButton:hover {{
                    background-color: #4a4a4a;
                }}
                #pageActionButton:pressed {{
                    background-color: #5a5a5a;
                }}
                QScrollBar:vertical, QScrollBar:horizontal {{
                    border: none;
                    background-color: #1a1a1a;
                    width: 10px;
                    height: 10px;
                    margin: 0px 0px 0px 0px;
                }}
                QScrollBar::handle:vertical, QScrollBar::handle:horizontal {{
                    background-color: #808080;
                    min-height: 20px;
                    min-width: 20px;
                    border-radius: 5px;
                }}
                QScrollBar::handle:vertical:hover, QScrollBar::handle:horizontal:hover {{
                    background-color: #9a9a9a;
                }}
                QScrollBar::handle:vertical:pressed, QScrollBar::handle:horizontal:pressed {{
                    background-color: #b0b0b0;
                }}
                QScrollBar::add-line:vertical, QScrollBar::sub-line:vertical,
                QScrollBar::add-line:horizontal, QScrollBar::sub-line:horizontal {{
                    border: none;
                    background: none;
                }}
                QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical,
                QScrollBar::add-page:horizontal, QScrollBar::sub-page:horizontal {{
                    background: none;
                }}
            """
        self.setStyleSheet(style_sheet)

    def _connect_signals(self):
        """连接所有信号到槽"""
        self.log_signal.connect(self._update_log)
        self.command_input.returnPressed.connect(self._send_command)
        
        self.sidebar_list.currentRowChanged.connect(self._handle_sidebar_change)
        
        # 初始选中第一个项目
        self.sidebar_list.setCurrentRow(0)

    def _handle_sidebar_change(self, index):
        """处理侧边栏切换，并控制日志面板的显示/隐藏"""
        self.content_stacked_widget.setCurrentIndex(index)
        if index == 0:  # 主页
            self.right_widget.show()
        else:
            self.right_widget.hide()

    def _create_home_page(self):
        """创建“主页”页面，包含跳转按钮"""
        page = QWidget()
        main_layout = QVBoxLayout(page)
        
        # 服务器路径和启动/停止部分
        path_group = QGroupBox("选择服务器/启动")
        path_group_layout = QVBoxLayout(path_group)
        self.path_label = QLabel("未选择路径")
        self.path_label.setWordWrap(True)
        self.path_btn = QPushButton("选择服务器路径")
        self.path_btn.setObjectName("actionButton")
        self.path_btn.clicked.connect(self._select_directory)
        
        start_stop_layout = QHBoxLayout()
        self.execute_btn_start = QPushButton("启动服务器")
        self.execute_btn_start.setObjectName("actionButton")
        self.execute_btn_start.clicked.connect(self._launch_server)
        self.stop_btn = QPushButton("停止服务器")
        self.stop_btn.setObjectName("actionButton")
        self.stop_btn.hide()
        self.stop_btn.clicked.connect(self._stop_server)
        
        start_stop_layout.addWidget(self.execute_btn_start)
        start_stop_layout.addWidget(self.stop_btn)
        
        path_group_layout.addWidget(self.path_label)
        path_group_layout.addWidget(self.path_btn)
        path_group_layout.addLayout(start_stop_layout)
        main_layout.addWidget(path_group)
        
        # 在两个组之间添加可伸缩空间
        main_layout.addStretch(1)

        # 跳转入口按钮部分
        entry_group = QGroupBox("功能")
        entry_layout = QVBoxLayout(entry_group)
        
        download_btn_entry = QPushButton("下载服务端")
        download_btn_entry.setObjectName("pageActionButton")
        download_btn_entry.clicked.connect(lambda: self.content_stacked_widget.setCurrentIndex(3))
        
        mem_btn_entry = QPushButton("配置内存")
        mem_btn_entry.setObjectName("pageActionButton")
        mem_btn_entry.clicked.connect(lambda: self.content_stacked_widget.setCurrentIndex(4))
        
        config_btn_entry = QPushButton("修改配置")
        config_btn_entry.setObjectName("pageActionButton")
        config_btn_entry.clicked.connect(lambda: self.content_stacked_widget.setCurrentIndex(5))

        entry_layout.addWidget(download_btn_entry)
        entry_layout.addWidget(mem_btn_entry)
        entry_layout.addWidget(config_btn_entry)

        main_layout.addWidget(entry_group)
        # 移除第二个 addStretch(1) 以确保该组在最底部
        # main_layout.addStretch(1)

        return page

    def _create_settings_page(self):
        """创建“设置”页面"""
        page = QWidget()
        layout = QVBoxLayout(page)
        
        theme_group = QGroupBox("主题设置")
        theme_layout = QVBoxLayout(theme_group)
        theme_layout.addWidget(QLabel("选择应用主题:"))
        self.theme_combo = QComboBox()
        self.theme_combo.addItems(["亮色", "暗色"])
        self.theme_combo.setCurrentText("亮色" if self.current_theme == "light" else "暗色")
        self.theme_combo.currentTextChanged.connect(self._change_theme)
        theme_layout.addWidget(self.theme_combo)
        layout.addWidget(theme_group)

        # 新增日志栏颜色设置
        log_color_group = QGroupBox("日志栏颜色")
        log_color_layout = QHBoxLayout()
        self.log_color_checkbox = QCheckBox("使用深色日志背景")
        self.log_color_checkbox.setChecked(self.log_is_dark)
        self.log_color_checkbox.stateChanged.connect(self._update_log_color)
        log_color_layout.addWidget(self.log_color_checkbox)
        log_color_group.setLayout(log_color_layout)
        layout.addWidget(log_color_group)

        custom_args_group = QGroupBox("启动参数")
        custom_args_layout = QVBoxLayout(custom_args_group)
        custom_args_layout.addWidget(QLabel("添加额外的服务器启动参数："))
        self.custom_args_input = QLineEdit()
        self.custom_args_input.setPlaceholderText("例如: -Dfile.encoding=UTF-8 --port 25565")
        custom_args_layout.addWidget(self.custom_args_input)
        layout.addWidget(custom_args_group)

        # 新增的停止超时设置
        stop_timeout_group = QGroupBox("服务器停止设置")
        stop_timeout_layout = QVBoxLayout(stop_timeout_group)

        self.force_stop_checkbox = QCheckBox("按下停止服务器后，超时强制停止服务器")
        stop_timeout_layout.addWidget(self.force_stop_checkbox)

        timeout_layout = QHBoxLayout()
        timeout_layout.addWidget(QLabel("超时时间 (秒):"))
        self.stop_timeout_input = QLineEdit()
        self.stop_timeout_input.setPlaceholderText("例如: 30")
        self.stop_timeout_input.setFixedWidth(50)
        timeout_layout.addWidget(self.stop_timeout_input)
        timeout_layout.addStretch()
        stop_timeout_layout.addLayout(timeout_layout)
        
        layout.addWidget(stop_timeout_group)

        # 新增的保存按钮
        save_btn = QPushButton("保存设置")
        save_btn.setObjectName("actionButton")
        save_btn.clicked.connect(self._save_settings)
        layout.addWidget(save_btn)
        
        layout.addStretch(1)
        return page

    def _create_about_page(self):
        """创建“关于”页面，展示Markdown内容，并让其占据全高"""
        page = QWidget()
        layout = QVBoxLayout(page)
        
        about_group = QGroupBox("关于")
        about_layout = QVBoxLayout(about_group)
        
        about_text = QTextBrowser()
        about_text.setOpenExternalLinks(True)
        about_text.setHtml("""
            <h1>Minecraft简易服务器部署工具MCSEasy</h1>
            <h3>版本1.2.0.0-RC1-GUIRefactor</h3>
            <hr>
            <h4>项目开发：</h4>
            <p><a href="https://github.com/GoldenHoe">GoldenHoe[↗]</a></p>
            <p><a href="https://github.com/HOE-Software-Team">HOE Software Team[↗]</a></p>
            <h4>开源协议：</h4>
            <p><a href="https://github.com/GoldenHoe/MCSEasy/blob/main/LICENSE">MIT License[↗]</a></p>
            <p>版权所有©2024-2025 HOE Software Team</p>
        """)
        
        about_layout.addWidget(about_text)
        about_group.setLayout(about_layout)
        layout.addWidget(about_group)
        
        return page

    def _create_download_page(self):
        """创建“下载服务端”页面"""
        page = QWidget()
        layout = QVBoxLayout(page)
        
        # 添加返回按钮
        back_btn = QPushButton("返回主页")
        back_btn.setObjectName("pageActionButton")
        back_btn.clicked.connect(lambda: self.content_stacked_widget.setCurrentIndex(0))
        layout.addWidget(back_btn)
        
        group = QGroupBox("下载服务端")
        group_layout = QVBoxLayout(group)
        group_layout.addWidget(QLabel("选择服务端版本:"))
        self.version_combo = QComboBox()
        self.version_combo.addItems(self.version_list)
        self.download_action_btn = QPushButton("开始下载")
        self.download_action_btn.setObjectName("actionButton")
        self.download_action_btn.clicked.connect(self._download_server)
        group_layout.addWidget(self.version_combo)
        group_layout.addWidget(self.download_action_btn)
        layout.addWidget(group)
        
        layout.addStretch(1)
        return page

    def _create_memory_page(self):
        """创建“配置内存”页面"""
        page = QWidget()
        layout = QVBoxLayout(page)

        # 添加返回按钮
        back_btn = QPushButton("返回主页")
        back_btn.setObjectName("pageActionButton")
        back_btn.clicked.connect(lambda: self.content_stacked_widget.setCurrentIndex(0))
        layout.addWidget(back_btn)

        group = QGroupBox("配置内存")
        group_layout = QVBoxLayout(group)
        group_layout.addWidget(QLabel("最小内存(GB):"))
        self.mem_min = QLineEdit()
        group_layout.addWidget(self.mem_min)
        group_layout.addWidget(QLabel("最大内存(GB):"))
        self.mem_max = QLineEdit()
        group_layout.addWidget(self.mem_max)
        self.mem_btn = QPushButton("保存配置")
        self.mem_btn.setObjectName("actionButton")
        self.mem_btn.clicked.connect(self._configure_memory)
        group_layout.addWidget(self.mem_btn)
        layout.addWidget(group)

        layout.addStretch(1)
        return page

    def _create_config_page(self):
        """创建“修改服务器配置”页面"""
        self.config_page = QWidget()
        layout = QVBoxLayout(self.config_page)
        
        # 添加返回按钮
        back_btn = QPushButton("返回主页")
        back_btn.setObjectName("pageActionButton")
        back_btn.clicked.connect(lambda: self.content_stacked_widget.setCurrentIndex(0))
        layout.addWidget(back_btn)

        load_group = QGroupBox("加载配置文件")
        load_layout = QVBoxLayout(load_group)
        load_layout.addWidget(QLabel("点击按钮加载或重新加载 server.properties 文件。"))
        self.load_config_btn = QPushButton("加载配置文件")
        self.load_config_btn.setObjectName("actionButton")
        self.load_config_btn.clicked.connect(self._load_server_config)
        load_layout.addWidget(self.load_config_btn)
        layout.addWidget(load_group)
        
        config_group = QGroupBox("修改配置")
        config_layout = QVBoxLayout(config_group)
        self.config_scroll_area = QScrollArea()
        self.config_scroll_area.setWidgetResizable(True)
        self.config_scroll_content = QWidget()
        self.config_layout = QVBoxLayout(self.config_scroll_content)
        self.config_scroll_area.setWidget(self.config_scroll_content)
        config_layout.addWidget(self.config_scroll_area)

        btn_group = QWidget()
        btn_layout = QHBoxLayout(btn_group)
        self.save_btn = QPushButton("保存配置")
        self.save_btn.setObjectName("actionButton")
        self.save_btn.clicked.connect(self._save_server_config)
        self.revert_btn = QPushButton("撤销更改")
        self.revert_btn.clicked.connect(self._load_server_config)
        btn_layout.addWidget(self.revert_btn)
        btn_layout.addWidget(self.save_btn)
        config_layout.addWidget(btn_group)
        layout.addWidget(config_group)

        return self.config_page

    def _change_theme(self, theme_name):
        """切换亮色/暗色主题"""
        self.current_theme = "dark" if theme_name == "暗色" else "light"
        self._apply_styles()
    
    def _update_log_color(self, state):
        """根据复选框状态更新日志颜色"""
        self.log_is_dark = self.log_color_checkbox.isChecked()
        self._apply_styles()

    def _load_settings(self):
        """加载保存的配置"""
        settings = QSettings("MyServerApp", "ServerDeployWindow")
        self.current_theme = settings.value("theme", "light")
        self.log_is_dark = settings.value("log_is_dark", True, type=bool)
        path = settings.value("path", "")
        self.path_label.setText(path if path else "未选择路径")
        self.mem_min.setText(settings.value("min_mem", ""))
        self.mem_max.setText(settings.value("max_mem", ""))
        if hasattr(self, 'custom_args_input'):
            self.custom_args_input.setText(settings.value("custom_args", ""))
        if hasattr(self, 'force_stop_checkbox'):
            self.force_stop_checkbox.setChecked(settings.value("force_stop_on_timeout", False, type=bool))
        if hasattr(self, 'stop_timeout_input'):
            self.stop_timeout_input.setText(settings.value("stop_timeout", "30"))
        if hasattr(self, 'theme_combo'):
            self.theme_combo.setCurrentText("亮色" if self.current_theme == "light" else "暗色")
        if hasattr(self, 'log_color_checkbox'):
            self.log_color_checkbox.setChecked(self.log_is_dark)
        self.log_signal.emit("[MCSEasy-INFO] 已加载保存的配置")

    def _save_settings(self):
        """保存当前配置到文件"""
        settings = QSettings("MyServerApp", "ServerDeployWindow")
        settings.setValue("path", self.path_label.text())
        settings.setValue("min_mem", self.mem_min.text())
        settings.setValue("max_mem", self.mem_max.text())
        settings.setValue("custom_args", self.custom_args_input.text())
        settings.setValue("force_stop_on_timeout", self.force_stop_checkbox.isChecked())
        settings.setValue("stop_timeout", self.stop_timeout_input.text())
        settings.setValue("theme", self.current_theme)
        settings.setValue("log_is_dark", self.log_color_checkbox.isChecked())
        
        self.log_signal.emit("[MCSEasy-INFO] 配置已保存")
        QMessageBox.information(self, "成功", "设置已保存。")

    def _select_directory(self):
        """选择路径并更新对应页面的标签"""
        path = QFileDialog.getExistingDirectory(self, "选择路径")
        if not path:
            return
        self.path_label.setText(path)
        self._save_settings()

    def _update_log(self, message):
        """更新日志内容"""
        cursor = self.log_widget.textCursor()
        cursor.movePosition(QTextCursor.End)
        cursor.insertText(f"{message}\n")
        self.log_widget.setTextCursor(cursor)
        self.log_widget.ensureCursorVisible()

    def _find_server_jar(self, path):
        """
        在指定路径查找服务端jar文件
        优先匹配通用核心名称
        """
        try:
            files = [f for f in os.listdir(path) if f.endswith(".jar")]
            if not files:
                return None
            
            # 优先匹配特定的服务器类型
            priority_keywords = ['paper', 'fabric', 'forge', 'bukkit', 'server']
            for keyword in priority_keywords:
                for f in files:
                    if keyword in f.lower():
                        return f
            
            # 如果没有找到特定的，且只有一个jar文件，则使用该文件
            if len(files) == 1:
                return files[0]

            # 否则，提示用户手动选择
            return None
        except Exception as e:
            logger.error(f"查找服务器jar文件失败: {e}")
            return None

    def _launch_server(self):
        """启动服务器"""
        path = self.path_label.text()
        if not path or not os.path.exists(path):
            QMessageBox.critical(self, "错误", "无效的服务器路径。")
            return

        server_jar = self._find_server_jar(path)
        if not server_jar:
            QMessageBox.critical(self, "错误", "未找到服务器核心文件(.jar)。")
            return

        self._modify_eula(path)
        
        try:
            os.chdir(path)
            
            jvm_args = []
            server_args = []
            
            # 始终将 JVM 参数 -Dfile.encoding=UTF-8 作为默认值
            jvm_args.append("-Dfile.encoding=UTF-8")
            
            min_mem = self.mem_min.text()
            max_mem = self.mem_max.text()
            
            # 如果没有设置内存，使用默认值
            if not min_mem.isdigit() or not max_mem.isdigit():
                jvm_args.extend(["-Xms2048M", "-Xmx4096M"])
                self.log_signal.emit("[MCSEasy-INFO] 未配置内存，将使用默认参数：-Xms2048M -Xmx4096M")
            else:
                jvm_args.extend([f"-Xms{min_mem}G", f"-Xmx{max_mem}G"])
            
            # 解析自定义参数，并区分JVM参数和服务器参数
            custom_args_text = self.custom_args_input.text().strip()
            if custom_args_text:
                custom_args_list = custom_args_text.split()
                for arg in custom_args_list:
                    if arg.startswith(('-X', '-D')):
                        jvm_args.append(arg)
                    else:
                        server_args.append(arg)
            
            # 始终将 --nogui 参数作为服务器参数
            server_args.insert(0, "--nogui")
            
            # 组合最终启动参数
            all_args = jvm_args + ["-jar", server_jar] + server_args
            
            self.server_process = QProcess()
            self.server_process.setProcessChannelMode(QProcess.MergedChannels)
            self.server_process.readyReadStandardOutput.connect(self._handle_process_output)
            self.server_process.finished.connect(self._on_server_stopped)
            
            self.execute_btn_start.hide()
            self.stop_btn.show()
            
            self.log_signal.emit(f"[MCSEasy-INFO] 启动命令: java {' '.join(all_args)}")
            self.server_process.start("java", all_args)
            self._update_server_status(True)
            self.log_signal.emit("[MCSEasy-INFO] 服务器已启动")
        except Exception as e:
            self.log_signal.emit(f"[MCSEasy-ERROR] 启动失败: {e}")
            QMessageBox.critical(self, "错误", f"启动失败: {e}")
            logger.error(f'启动服务器失败: {e}')
    
    def _on_server_stopped(self):
        """服务器停止时的处理"""
        # 停止计时器，以防万一
        if self.stop_timer and self.stop_timer.isActive():
            self.stop_timer.stop()
            self.stop_timer.deleteLater()
            self.stop_timer = None

        self.execute_btn_start.show()
        self.stop_btn.hide()
        self._update_server_status(False)
        self.log_signal.emit("[MCSEasy-INFO] 服务器已停止")
        logger.info('服务器已停止')
    
    def _stop_server(self):
        """停止服务器"""
        if self.server_process and self.server_process.state() == QProcess.Running:
            self.server_process.write("stop\n".encode())
            
            if self.force_stop_checkbox.isChecked():
                timeout_str = self.stop_timeout_input.text()
                if timeout_str.isdigit():
                    timeout_seconds = int(timeout_str)
                    self.log_signal.emit(f"[MCSEasy-INFO] 已启用超时强制停止，超时时间为 {timeout_seconds} 秒")
                    self.stop_timer = QTimer(self)
                    self.stop_timer.setSingleShot(True)
                    self.stop_timer.timeout.connect(self._force_kill_server)
                    self.stop_timer.start(timeout_seconds * 1000)
                else:
                    self.log_signal.emit("[MCSEasy-WARN] 超时时间设置无效，将不启用强制停止")
        else:
            QMessageBox.warning(self, "警告", "服务器未在运行。")

    def _force_kill_server(self):
        """强制终止服务器进程"""
        if self.server_process and self.server_process.state() == QProcess.Running:
            self.server_process.kill()
            self.log_signal.emit("[MCSEasy-WARN] 已强制终止服务器进程")
            logger.warning('服务器进程被强制停止')

    def _send_command(self):
        """发送指令到服务器"""
        if self.server_process and self.server_process.state() == QProcess.Running:
            command = self.command_input.text()
            self.server_process.write(f"{command}\n".encode())
            self.command_input.clear()
        else:
            QMessageBox.warning(self, "警告", "服务器未在运行，无法发送指令。")

    def _handle_process_output(self):
        """处理进程输出"""
        if self.server_process:
            output = self.server_process.readAllStandardOutput().data().decode("gbk", errors='replace')
            self.log_signal.emit(output.strip())

    def _download_server(self):
        """下载服务器文件"""
        path = self.path_label.text()
        version = self.version_combo.currentText()
        
        if not path or path == "未选择路径":
            QMessageBox.critical(self, "错误", "请先选择安装路径")
            return
        
        try:
            index = self.version_list.index(version)
            url = self.url_list[index]
        except ValueError:
            QMessageBox.critical(self, "错误", "无效的版本选择")
            return

        try:
            urllib.request.urlopen('http://connectivitycheck.gstatic.com/generate_204', timeout=5)
        except Exception:
            QMessageBox.critical(self, "错误", "网络连接异常，请检查您的网络设置。")
            return

        self.download_thread = DownloadThread(url, path)
        self.download_thread.progress_updated.connect(lambda p: self.download_action_btn.setText(f"下载中... {p}%"))
        self.download_thread.download_finished.connect(self._on_download_finished)
        self.download_action_btn.setEnabled(False)
        self.download_thread.start()
        
    def _on_download_finished(self, success: bool, message: str):
        """下载完成时的处理"""
        self.download_action_btn.setEnabled(True)
        self.download_action_btn.setText("开始下载")
        if success:
            QMessageBox.information(self, "完成", f"服务端已保存至:\n{message}")
            logger.info(f'下载完毕，服务器文件保存至: {message}')
        else:
            QMessageBox.critical(self, "错误", f"下载失败: {message}")
            logger.error(f'下载失败: {message}')
            
    def _configure_memory(self):
        """配置内存并保存"""
        min_mem_str = self.mem_min.text()
        max_mem_str = self.mem_max.text()
        
        if not (min_mem_str.isdigit() and max_mem_str.isdigit()):
            QMessageBox.critical(self, "错误", "请输入有效的数字")
            return
            
        min_mem = int(min_mem_str)
        max_mem = int(max_mem_str)
        
        if max_mem <= min_mem:
            QMessageBox.critical(self, "错误", "最大内存必须大于最小内存")
            return

        self._save_settings()

    def _modify_eula(self, path: str):
        """修改eula.txt以同意协议"""
        eula_path = os.path.join(path, EULA_FILE_NAME)
        if os.path.exists(eula_path):
            try:
                with open(eula_path, "r", encoding='utf-8') as f:
                    content = f.read()
                if "eula=false" in content.lower():
                    with open(eula_path, 'w', encoding='utf-8') as f:
                        f.write(content.replace("eula=false","eula=true"))
                    self.log_signal.emit("[MCSEasy-INFO] 已自动同意EULA协议")
                    logger.info('自动同意EULA成功')
            except Exception as e:
                logger.error(f'自动同意EULA失败: {e}')

    def _load_server_config(self):
        """加载服务器配置并生成UI控件"""
        path = self.path_label.text()
        if not path or not os.path.exists(path):
            QMessageBox.warning(self, "警告", "请先选择有效的服务器路径")
            return
        
        for widget in reversed(range(self.config_layout.count())):
            item = self.config_layout.takeAt(widget)
            if item.widget():
                item.widget().deleteLater()
        
        prop_path = os.path.join(path, SERVER_PROPERTIES_FILE)
        self.original_config = {}

        if os.path.exists(prop_path):
            try:
                with open(prop_path, 'r', encoding='gbk', errors='ignore') as f:
                    for line in f:
                        line = line.strip()
                        if line and not line.startswith('#'):
                            key_val = line.split('=', 1)
                            if len(key_val) == 2:
                                self.original_config[key_val[0]] = key_val[1]
            except Exception as e:
                logger.error(f'配置文件读取失败: {e}')
                QMessageBox.critical(self, "错误", f"读取 server.properties 失败: {e}")
                return

        self.config_controls = {}
        for key, value in self.original_config.items():
            widget = QWidget()
            layout = QHBoxLayout(widget)
            layout.setContentsMargins(0, 0, 0, 0)
            
            label = QLabel(f"{key}:")
            label.setFixedWidth(200)
            layout.addWidget(label)
            
            if value.lower() in ['true', 'false']:
                combo = QComboBox()
                combo.addItems(['true', 'false'])
                combo.setCurrentText(value)
                combo.currentTextChanged.connect(self._on_config_changed)
                self.config_controls[key] = combo
                layout.addWidget(combo)
            else:
                edit = QLineEdit()
                edit.setText(value)
                edit.textChanged.connect(self._on_config_changed)
                self.config_controls[key] = edit
                layout.addWidget(edit)
                
            self.config_layout.addWidget(widget)

        self.config_layout.addStretch(1)
        self.has_unsaved_changes = False

    def _on_config_changed(self, text=None):
        """检查是否有未保存的更改"""
        self.has_unsaved_changes = any(
            (c.currentText() if isinstance(c, QComboBox) else c.text()) != self.original_config.get(k, "")
            for k, c in self.config_controls.items()
        )

    def _save_server_config(self):
        """保存服务器配置"""
        path = self.path_label.text()
        if not path:
            return
        
        prop_path = os.path.join(path, SERVER_PROPERTIES_FILE)
        
        try:
            with open(prop_path, 'w', encoding='utf-8') as f:
                for key, control in self.config_controls.items():
                    value = control.currentText() if isinstance(control, QComboBox) else control.text()
                    f.write(f"{key}={value}\n")
            
            self.log_signal.emit("[MCSEasy-INFO] 服务器配置已更新")
            logger.info('服务器配置更新成功')
            self.has_unsaved_changes = False
            QMessageBox.information(self, "成功", "配置文件已保存。")
        except Exception as e:
            QMessageBox.critical(self, "错误", f"保存配置失败: {e}")
            logger.error(f'保存配置失败: {e}')

    def create_status_label(self, layout):
        """创建状态标签"""
        self.status_label = QLabel("已停止")
        self.status_label.setObjectName("status_label")
        self.status_label.setAlignment(Qt.AlignCenter)
        self.status_label.setFixedWidth(100)
    
        log_header_layout = QHBoxLayout()
        log_header_label = QLabel("服务器日志输出:")
        log_header_layout.addWidget(log_header_label)
        log_header_layout.addStretch()
        log_header_layout.addWidget(self.status_label)

        container = QWidget()
        container.setLayout(log_header_layout)
        layout.addWidget(container)
    
    def _update_server_status(self, is_running: bool):
        """更新服务器状态显示"""
        self.server_running = is_running
        if is_running:
            self.status_label.setText("运行中")
            self.status_label.setStyleSheet("#status_label { background-color: #6FCF97; }")
        else:
            self.status_label.setText("已停止")
            self.status_label.setStyleSheet("#status_label { background-color: #EB5757; }")

if __name__ == "__main__":
    app = QApplication(sys.argv)
    app_font = QFont("Microsoft YaHei")
    app.setFont(app_font)
    window = ServerDeployWindow()
    window.show()
    check_hardware()
    sys.exit(app.exec_())